dist: bionic

language: cpp

compiler:
  - gcc

addons:
  apt:
    packages:
    - libopencv-dev
    - libasio-dev

before_script:
  - sudo apt install libopencv-dev libasio-dev
  - bash -i install_openvslam.sh
  - source ~/.bashrc
  - mkdir build
  - cd build
  - cmake -DRUN_SLAM=ON ..

script:
  - make -j
