dist: bionic

language: cpp

compiler:
  - gcc

addons:
  apt:
    packages:
    - libopencv-dev
    - libasio-dev

before_script:
  - sudo apt install libopencv-dev libasio-dev
  - mkdir build
  - cd build
  - cmake ..

script:
  - make -j
