dist: bionic

language: cpp

compiler:
  - gcc

addons:
  apt:
    packages:
    - libopencv-dev
    - libasio-dev
    - xterm
    - libyaml-cpp-dev

before_script:
  - sudo apt install libopencv-dev libasio-dev xterm libyaml-cpp-dev
  - bash -i scripts/install_openvslam.sh
  - source ~/.bashrc
  - mkdir build
  - cd build
  - cmake -DRUN_SLAM=ON -DUSE_TERMINAL=ON -DUSE_CONFIG=ON ..

script:
  - make -j
