# Sample tello camera config file

#==============#
# Camera Model #
#==============#

Camera.name: "Tello"
Camera.setup: "monocular"
Camera.model: "perspective"

Camera.fx: 1843.37401
Camera.fy: 1858.58782
Camera.cx: 545.155626
Camera.cy: 445.740028

Camera.k1: 0.561939658
Camera.k2: -5.76385255
Camera.p1: 0.0356825441
Camera.p2: 0.0108696501
Camera.k3: 32.9089203

Camera.fps: 30.0
Camera.cols: 960
Camera.rows: 720

Camera.color_order: "BGR"

#================#
# orb parameters #
#================#

Feature.max_num_keypoints: 2000
Feature.scale_factor: 1.2
Feature.num_levels: 8
Feature.ini_fast_threshold: 20
Feature.min_fast_threshold: 7

#========================#
# Initializer Parameters #
#========================#

Initializer.scaling_factor: 5.0
